// Code generated by "stringer -type lifecycleState -trimprefix lifecycle"; DO NOT EDIT.

package controller

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[lifecycleNew-0]
	_ = x[lifecycleAlive-1]
	_ = x[lifecycleDying-2]
	_ = x[lifecycleDead-3]
}

const _lifecycleState_name = "NewAliveDyingDead"

var _lifecycleState_index = [...]uint8{0, 3, 8, 13, 17}

func (i lifecycleState) String() string {
	if i < 0 || i >= lifecycleState(len(_lifecycleState_index)-1) {
		return "lifecycleState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _lifecycleState_name[_lifecycleState_index[i]:_lifecycleState_index[i+1]]
}
