// Code generated by "stringer -type=runState -trimprefix runState"; DO NOT EDIT.

package controller

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[runStateNew-0]
	_ = x[runStateAlive-1]
	_ = x[runStateDying-2]
	_ = x[runStateDead-3]
}

const _runState_name = "NewAliveDyingDead"

var _runState_index = [...]uint8{0, 3, 8, 13, 17}

func (i runState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_runState_index)-1 {
		return "runState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _runState_name[_runState_index[idx]:_runState_index[idx+1]]
}
