// Code generated by "stringer -type ChanReadStatus -trimprefix ChanReadStatus"; DO NOT EDIT.

package testutil

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ChanReadStatusClosed-1]
	_ = x[ChanReadStatusBlocked-2]
	_ = x[ChanReadStatusOk-3]
}

const _ChanReadStatus_name = "ClosedBlockedOk"

var _ChanReadStatus_index = [...]uint8{0, 6, 13, 15}

func (i ChanReadStatus) String() string {
	i -= 1
	if i < 0 || i >= ChanReadStatus(len(_ChanReadStatus_index)-1) {
		return "ChanReadStatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ChanReadStatus_name[_ChanReadStatus_index[i]:_ChanReadStatus_index[i+1]]
}
