// Code generated by "stringer -type=ChanReadStatus -trimprefix ChanReadStatus"; DO NOT EDIT.

package testutil

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ChanReadStatusOk-1]
	_ = x[ChanReadStatusBlocked-2]
	_ = x[ChanReadStatusClosed-3]
}

const _ChanReadStatus_name = "OkBlockedClosed"

var _ChanReadStatus_index = [...]uint8{0, 2, 9, 15}

func (i ChanReadStatus) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_ChanReadStatus_index)-1 {
		return "ChanReadStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChanReadStatus_name[_ChanReadStatus_index[idx]:_ChanReadStatus_index[idx+1]]
}
